config-version = 2
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 60
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
automatically-unhide-macos-hidden-apps = false

after-startup-command = [
  "exec-and-forget /opt/homebrew/bin/borders active_color=0xffd08770 inactive_color=0x00494d64 width=10.0 hidpi=on blacklist='Microsoft PowerPoint'",
  "exec-and-forget /opt/homebrew/bin/aerospace reload-config",
]

# __CORE_AEROSPACE_PERSISTENT_WORKSPACES__

[key-mapping]
preset = "qwerty"

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
alt-slash = "layout tiles horizontal vertical"
alt-comma = "layout accordion horizontal vertical"

alt-e = "focus left"
alt-i = "focus down"
alt-l = "focus up"
alt-a = "focus right"
alt-shift-e = "move left"
alt-shift-i = "move down"
alt-shift-l = "move up"
alt-shift-a = "move right"

alt-minus = "resize smart -50"
alt-semicolon = "resize smart +50"

# __CORE_AEROSPACE_WORKSPACE_BINDINGS__

alt-tab = "workspace-back-and-forth"
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
alt-shift-semicolon = "mode service"

# __CORE_AEROSPACE_MONITOR_ASSIGNMENTS__

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"]
f = ["layout floating tiling", "mode main"]
backspace = ["close-all-windows-but-current", "mode main"]
alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]

# __CORE_AEROSPACE_FLOATING_APP_RULES__
