matches:
  # 日時
  - trigger: ";now"
    replace: "{{now}}"
    vars:
      - name: "now"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";genz"
    replace: "現在（{{now}}）"
    vars:
      - name: "now"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";genj"
    replace: "現状（{{now}}）"
    vars:
      - name: "now"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";iso"
    replace: "{{iso}}"
    vars:
      - name: "iso"
        type: "date"
        params:
          format: "%Y-%m-%dT%H:%M:%S"
  - trigger: ";ts"
    replace: "{{ts}}"
    vars:
      - name: "ts"
        type: "date"
        params:
          format: "%Y%m%d%H%M%S"
  - trigger: ";end"
    replace: "23:59"

  # Obsidian
  - trigger: ";ot"
    replace: "➕ {{today}} 🛫 {{today}}"
    vars:
      - name: "today"
        type: "date"
        params:
          format: "%Y-%m-%d"
  - trigger: ";["
    replace: "[[$|$]]"

  # 絵文字
  - trigger: ";gd"
    replace: "👍️"
  - trigger: ";plz"
    replace: "🙏"
  - trigger: ";ok"
    replace: "👌"
  - trigger: ";pw"
    replace: "💪"

  # テキスト
  - trigger: ";ps"
    replace: "projects"
  - trigger: ";dd"
    replace: "Downloads"
  - trigger: ";lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
  - trigger: ";thx"
    replace: "ありがとうございます"
  - trigger: ";ack"
    replace: "承知しました"

  # 記号
  - trigger: ";;"
    replace: "_"
  - trigger: ";-"
    replace: "|"
  - trigger: ";."
    replace: "/"
  - trigger: ";v "
    replace: "- "
  - trigger: ";vc"
    replace: "---"

  # ネットワーク
  - trigger: ";lh"
    replace: "http://localhost:"
  - trigger: ";li"
    replace: "http://127.0.0.1:"

  # クリップボード活用
  - regex: ";cb(?P<lang>\\w*) "
    replace: "```{{lang}}\n{{clipboard}}\n```"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ";ci"
    replace: "`{{clipboard}}`"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # コマンド
  - regex: ";z(?P<session>\\w+) "
    replace: "zellij a -c {{session}}"
  - trigger: ";gc "
    replace: 'git commit -m "$|$"'
  - trigger: ";gcft"
    replace: 'git commit -m "feat: $|$"'
  - trigger: ";gcfx"
    replace: 'git commit -m "fix: $|$"'
  - trigger: ";gcrf"
    replace: 'git commit -m "refactor: $|$"'
  - trigger: ";gcch"
    replace: 'git commit -m "chore: $|$"'
  - trigger: ";gcdc"
    replace: 'git commit -m "docs: $|$"'
  - trigger: ";gcci"
    replace: 'git commit -m "ci: $|$"'
  - trigger: ";gcts"
    replace: 'git commit -m "test: $|$"'
  - trigger: ";gom"
    replace: "origin/main"

  # AI
  - trigger: ";aib"
    replace: "壁打ちしてください。"
  - trigger: ";aisi"
    replace: "簡潔に回答してください。"
  - trigger: ";aii"
    replace: "改善案を示してください。"
  - trigger: ";air"
    replace: "調査してください。"
  - trigger: ";aiwr"
    replace: "Webを調査してください。"
  - trigger: ";aif"
    replace: "修正してください。"
  - trigger: ";ait"
    replace: "対応してください。"
  - trigger: ";aine"
    replace: "編集は不要です。"
  - trigger: ";aism"
    replace: "整理してください。"
  - trigger: ";aisr"
    replace: "セルフレビューしてください。"
  - trigger: ";aia"
    replace: "アドバイスしてください。"
  - trigger: ";aieis"
    replace: "簡単に説明してください。"
  - trigger: ";aicap"
    replace: "コミットして、プッシュしてください。"
  - trigger: ";aija"
    replace: "これはただの質問です。"

  # Neovim
  - trigger: ";vy"
    replace: "%y+\n"

  # ファイル名
  - trigger: ";fdc"
    replace: "docker-compose.yaml"
  - trigger: ";fdf"
    replace: "Dockerfile"
  - trigger: ";fgi"
    replace: ".gitignore"
  - trigger: ";frm"
    replace: "README.md"
  - trigger: ";fcl"
    replace: "CHANGELOG.md"
  - trigger: ";fjf"
    replace: "justfile"
  - trigger: ";fmi"
    replace: "mise.toml"
  - trigger: ";fcs"
    replace: "cspell.json"
